CREATE TABLE [dbo].[Nominal]
(
	[Id]		INT		NOT NULL IDENTITY (1, 1),
	[Value]		MONEY	NOT NULL UNIQUE,
	[IsDefault] BIT		NOT NULL DEFAULT(0),

	CONSTRAINT [PK_dbo.Nominal] PRIMARY KEY CLUSTERED ([Id] ASC)
)
